### ISSUE TITLE
filter all non-RFC Chars for emails

### ISSUE THREAD

**Issue by PfiatDe** [rosegabe/employeexing#1]
Internet email addresses must include only RFC-compliant characters, which include:
    Numbers 0-9
    Uppercase letters A-Z
    Lowercase letters a-z
    Plus sign +
    Hyphen -
    Underscore _
    Tilde ~

There is already a filter in place however, something like "é", "è", "ê" should also get substituted.

**Comment by rosegabe** [comment]
Thank you. I have added a filter for the described use case.
